// Mocks generated by Mockito 5.4.6 from annotations
// in hotspot_partner_app/test/providers/billing_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hotspot_partner_app/repositories/transaction_repository.dart'
    as _i4;
import 'package:hotspot_partner_app/repositories/wallet_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i2.WalletRepository {
  MockWalletRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>?> fetchBalance() =>
      (super.noSuchMethod(
            Invocation.method(#fetchBalance, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> fetchCounters() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCounters, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<dynamic>> fetchPlans() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPlans, []),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<dynamic>> fetchAllTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllTransactions, []),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<dynamic>> fetchTransactions({
    String? search,
    String? status,
    String? type,
    String? period,
    String? startDate,
    String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTransactions, [], {
              #search: search,
              #status: status,
              #type: type,
              #period: period,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<dynamic>> fetchWithdrawals({
    String? search,
    String? status,
    String? period,
    String? startDate,
    String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWithdrawals, [], {
              #search: search,
              #status: status,
              #period: period,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> createWithdrawal(
    Map<String, dynamic>? requestData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createWithdrawal, [requestData]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> fetchTransactionDetails(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTransactionDetails, [transactionId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i4.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<dynamic>> fetchTransactions({
    String? search,
    String? status,
    String? type,
    String? period,
    String? startDate,
    String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTransactions, [], {
              #search: search,
              #status: status,
              #type: type,
              #period: period,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<dynamic>> fetchAdditionalDeviceTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAdditionalDeviceTransactions, []),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<dynamic>> fetchAssignedPlanTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAssignedPlanTransactions, []),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getAssignedTransactionDetails(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAssignedTransactionDetails, [id]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getWalletTransactionDetails(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWalletTransactionDetails, [id]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getAssignedWalletBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getAssignedWalletBalance, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<dynamic>> getAssignedWalletTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getAssignedWalletTransactions, []),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getWalletBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getWalletBalance, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<dynamic>> getWalletTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getWalletTransactions, []),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getTransactionDetails(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionDetails, [id]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<dynamic>> getWithdrawals() =>
      (super.noSuchMethod(
            Invocation.method(#getWithdrawals, []),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> createWithdrawal(
    Map<String, dynamic>? withdrawalData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createWithdrawal, [withdrawalData]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
